### ISSUE TITLE
Arama Button Responsive Değil!

### ISSUE THREAD

**Issue by ghost** [muhammedzaimtr/Minimal-Wordpress-Temasi#1]
Arama butonu ve arama yazma kısmı responsive değil 
![Demo](https://cloud.githubusercontent.com/assets/8466533/14831611/2b4da634-0bff-11e6-9b55-fccc7796c25f.jpg)
@muhammedzaimtr

**Comment by muhammedzaimtr** [comment]
Sorun Giderildi :) Teşekkürler
